name: Publish & Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0 or 3.0.0-alpha.
      # For more details, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      # and https://docs.npmjs.com/about-semantic-versioning

jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          npm --prefix bin ci
          npm --prefix devServer ci
      - name: publish dev server
        if: contains(github.ref, 'rc') == false
        run: npm publish --tag latest
        working-directory: ./devServer
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish dev server @next
        if: contains(github.ref, 'rc')
        run: npm publish --tag next
        working-directory: ./devServer
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
      - name: Create Prerelease
        if: contains(github.ref, 'rc')
        id: create_prerelease
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: true
      - name: Create Release
        if: contains(github.ref, 'rc') == false
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

